spring.application.name=application-service
server.port=8082

spring.datasource.url=${APPLICATION_DB_URL:jdbc:postgresql://localhost:5433/interviewflow_application}
spring.datasource.username=${APPLICATION_DB_USERNAME:postgres}
spring.datasource.password=${APPLICATION_DB_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

app.jwt.secret=${APP_JWT_SECRET:interviewflow-local-jwt-secret-key-with-32-chars-minimum}
app.kafka.topics.application-events=${APPLICATION_EVENTS_TOPIC:application-events}
app.kafka.topics.reminder-events=${REMINDER_EVENTS_TOPIC:reminder-events}

management.endpoints.web.exposure.include=health,info
