spring.application.name=api-gateway
server.port=${PORT:8090}

services.auth.url=${AUTH_SERVICE_SCHEME:http}://${AUTH_SERVICE_HOST}:${AUTH_SERVICE_PORT}
services.application.url=${APPLICATION_SERVICE_SCHEME:http}://${APPLICATION_SERVICE_HOST}:${APPLICATION_SERVICE_PORT}
services.notification.url=${NOTIFICATION_SERVICE_SCHEME:http}://${NOTIFICATION_SERVICE_HOST}:${NOTIFICATION_SERVICE_PORT}
app.cors.allowed-origin-patterns=${APP_CORS_ALLOWED_ORIGIN_PATTERNS}

management.endpoints.web.exposure.include=health,info
