spring.application.name=api-gateway
server.port=8090

services.auth.url=${AUTH_SERVICE_URL:http://localhost:8081}
services.application.url=${APPLICATION_SERVICE_URL:http://localhost:8082}
services.notification.url=${NOTIFICATION_SERVICE_URL:http://localhost:8083}
app.cors.allowed-origin-patterns=${APP_CORS_ALLOWED_ORIGIN_PATTERNS:http://localhost:3000,https://*.loca.lt,https://*.localtunnel.me}

management.endpoints.web.exposure.include=health,info
